### ISSUE TITLE
Possible improvement for 'num2si' method

### ISSUE THREAD

**Issue by OshinoMoumou** [AleCandido/Lab3#1]
Greetings!
I noticed that in BobLightyear.py, 'num2si' method referred a StackOverflow post, while a [recent comment](https://stackoverflow.com/questions/17973278/python-decimal-engineering-notation-for-mili-10e-3-and-micro-10e-6#comment68611688_19270863) to it mentioned that _for x=0, we need a case so something like if x==0: exp=0, exp3=0_.
I'm trying to learn the usefulness of such small updates on StackOverflow. Would this comment help improve your code? I understand that such defect might not happen in real life situation. In that case, do you think this comment can help prevent future bugs (for example, when the code were reused somewhere else)?
I'll really appreciate it if you could kindly give me some feedback or suggestions. Thank you very much for your time.
Have a nice day!

**Comment by alecandido** [comment]
First the most important thing: this repository is not archived only because I've been lazy, so there won't be any update ever (you can see the date of the last commit, and moreover it was just used for a university lab course years ago).
No problem for your issue, but it's not the best place to learn from (it has been written by undergrad students and never updated).

Then, as you can see the separate case already exists:
https://github.com/AleCandido/Lab3/blob/22ff834ee960628490dceac7836e43c75468399b/BobLightyear.py#L1050-L1051
`format` is a function parameter, with a sensible default, and this line is an [early return](https://www.google.com/search?q=early+return), that makes the code easier, since you don't need to account for everything that comes later, and the code is more decoupled (if you ever want to change the name or the meaning of `exp`, `exp3`, you don't need to change this line, so it's easier to understand, refactor, and maintain in general).

Then, `0` is such a special number that it's worth to account for it separately: it would not match other rules, since `log(0)` is undefined, and it might appear in real life cases, because maybe it won't be the result of any actual measure, but it might be your default value (or it can also appear as a result of measure, if what you're measuring is below the sensitivity of your instrument).
